### ISSUE TITLE
Hi! I'm reproducing your great work to cite your paper in my work. Could you please give more details about the hyperparameter settings for Yelp and Amazon?

### ISSUE THREAD

**Issue by XZJIsme** [blacksingular/GHRN#3]
I think it would be great to reproduce your work successfully and cite it in my work!
But I find it may be a little hard to get a result exacty same as the results reported in the paper.
It would help if you can give some good exp settings to me!
I tried like this:
```
python main.py --dataset yelp --del_ratio 0.1 --run 1 --load_epoch 200
python main.py --dataset amazon --del_ratio 0.015 --run 2 --load_epoch 40
```
Thanks again. Hope to get your valuable reply soon : )

**Comment by XZJIsme** [comment]
After posting this issue, I also tried this:
```
python main.py --dataset amazon --del_ratio 0.015 --run 5 --load_epoch 100 --homo 2 --epoch 300
```
The result on Amazon kinda pretty well, like `MF1-mean: 92.03, MF1-std: 0.70, AUC-mean: 96.10, AUC-std: 0.76`, almost close to the result in the paper, though still a little lower. But in similar way, on Yelp, seems still can't work well.

**Comment by blacksingular** [comment]
Hi there,
Thanks for your interest in our work. I guess the reason might be that you should set paramter **--homo** as **0** for YelpChi and Amazon dataset, since different relations are contained in the dataset.
